train:
  _target_: src.datasets.CustomDirAudioDataset
  audio_dir: "data/custom_dir/audio"
  transcription_dir: "data/custom_dir/transcriptions"
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.CustomDirAudioDataset
  audio_dir: "data/custom_dir/audio"
  transcription_dir: "data/custom_dir/transcriptions"
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.CustomDirAudioDataset
  audio_dir: "data/custom_dir/audio"
  transcription_dir: "data/custom_dir/transcriptions"
  instance_transforms: ${transforms.instance_transforms.inference}

