defaults:
  - model: deepspeech2
  - writer: cometml
  - metrics: example
  - datasets: example
  - dataloader: example
  - transforms: augs_strong
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 5e-3
  pct_start: 0.1
  steps_per_epoch: ${trainer.epoch_len}
  epochs: ${trainer.n_epochs}
  anneal_strategy: cos
loss_function:
  _target_: src.loss.CTCLossWrapper
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
trainer:
  log_step: 50
  n_epochs: 200
  epoch_len: 200
  device_tensors: ["spectrogram", "text_encoded"]
  resume_from: null
  device: auto
  override: False
  monitor: "min val_loss"
  save_period: 5
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1

