defaults:
  - model: deepspeech2
  - metrics: example
  - datasets: example_eval # we do not want to run inference on training data
  - dataloader: example
  - transforms: example
  - _self_
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "predictions" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/model_best.pth" # path to the pretrained model
