defaults:
  - model: deepspeech2
  - metrics: inference_metrics
  - datasets: example_eval
  - dataloader: example
  - transforms: inference
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
inferencer:
  device_tensors: ["spectrogram", "text_encoded"]
  device: auto
  save_path: "predictions"
  seed: 1
  from_pretrained: "saved/model_best.pth"
