train:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
  audio:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.Gain
        sample_rate: 16000
        p: 0.04
      - _target_: src.transforms.wav_augs.PitchShift
        sample_rate: 16000
        min_transpose_semitones: -2
        max_transpose_semitones: 2
        p: 0.04
      - _target_: src.transforms.wav_augs.Noise
        sample_rate: 16000
        min_snr_in_db: 5
        max_snr_in_db: 15
        p: 0.04
      - _target_: src.transforms.wav_augs.SpeedChange
        sample_rate: 16000
        speed_factor: 0.8
      - _target_: src.transforms.wav_augs.SpeedChange
        sample_rate: 16000
        speed_factor: 1.2
      - _target_: src.transforms.wav_augs.Shift
        sample_rate: 16000
        p: 0.04

inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
